[package]
name = "lux"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lumen = { path = "../lumen" }
pest = "2.5.2"
pest_derive = "2.5.2"
